package com.marceloaleixo.melvora.controller;
import com.marceloaleixo.melvora.dto.FinanceiroRequests; import com.marceloaleixo.melvora.entity.enums.*; import com.marceloaleixo.melvora.service.*;
import jakarta.validation.Valid; import java.time.LocalDate; import org.springframework.data.domain.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller public class FinanceiroController { private final FinanceiroService service; private final ModuloAcessoService mod; public FinanceiroController(FinanceiroService s,ModuloAcessoService m){service=s;mod=m;}
 @GetMapping("/financeiro") @PreAuthorize("hasAnyRole('ADMIN','RECEPCIONISTA')") public String index(@RequestParam(defaultValue="0") int page,Model model){mod.exigir(ModuloSistema.FINANCEIRO); LocalDate hoje=LocalDate.now(); model.addAttribute("pagina",service.listar(PageRequest.of(Math.max(0,page),20,Sort.by("dataMovimento").descending().and(Sort.by("id").descending())))); model.addAttribute("receitasHoje",service.total(hoje,hoje,TipoLancamentoFinanceiro.RECEITA)); model.addAttribute("despesasHoje",service.total(hoje,hoje,TipoLancamentoFinanceiro.DESPESA)); if(!model.containsAttribute("form"))model.addAttribute("form",new FinanceiroRequests.LancamentoForm(TipoLancamentoFinanceiro.DESPESA,null,"",hoje,hoje,null)); model.addAttribute("tipos",TipoLancamentoFinanceiro.values()); model.addAttribute("formas",FormaPagamento.values()); return "pages/financeiro"; }
 @PostMapping("/financeiro/lancamentos") @PreAuthorize("hasRole('ADMIN')") public String criar(@Valid @ModelAttribute("form") FinanceiroRequests.LancamentoForm form,BindingResult br,Model model,RedirectAttributes ra){mod.exigir(ModuloSistema.FINANCEIRO); if(br.hasErrors()){preparar(model);return "pages/financeiro";} try{service.criar(form);ra.addFlashAttribute("sucesso","Despesa registrada com sucesso.");return "redirect:/financeiro";}catch(RuntimeException e){preparar(model);model.addAttribute("erro",mensagem(e));return "pages/financeiro";} }
 @PostMapping("/financeiro/{id}/pagar") @PreAuthorize("hasAnyRole('ADMIN','RECEPCIONISTA')") public String pagar(@PathVariable Long id,@RequestParam FormaPagamento forma,RedirectAttributes ra){try{service.pagar(id,forma);ra.addFlashAttribute("sucesso","Lançamento marcado como pago.");}catch(RuntimeException e){ra.addFlashAttribute("erro",mensagem(e));}return "redirect:/financeiro";}
 @PostMapping("/financeiro/{id}/cancelar") @PreAuthorize("hasRole('ADMIN')") public String cancelar(@PathVariable Long id,RedirectAttributes ra){try{service.cancelar(id);ra.addFlashAttribute("sucesso","Lançamento cancelado.");}catch(RuntimeException e){ra.addFlashAttribute("erro",mensagem(e));}return "redirect:/financeiro";}
 private void preparar(Model m){LocalDate h=LocalDate.now();m.addAttribute("receitasHoje",service.total(h,h,TipoLancamentoFinanceiro.RECEITA));m.addAttribute("despesasHoje",service.total(h,h,TipoLancamentoFinanceiro.DESPESA));m.addAttribute("pagina",service.listar(PageRequest.of(0,20,Sort.by("dataMovimento").descending())));m.addAttribute("tipos",TipoLancamentoFinanceiro.values());m.addAttribute("formas",FormaPagamento.values());}
 private String mensagem(RuntimeException e){return e.getMessage()==null||e.getMessage().isBlank()?"Não foi possível concluir a operação.":e.getMessage();}}
