package com.marceloaleixo.melvora.service;
import com.marceloaleixo.melvora.dto.FinanceiroRequests; import com.marceloaleixo.melvora.entity.*; import com.marceloaleixo.melvora.entity.enums.*; import com.marceloaleixo.melvora.exception.*; import com.marceloaleixo.melvora.repository.*; import com.marceloaleixo.melvora.tenant.TenantContext;
import java.math.BigDecimal; import java.time.LocalDate; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class FinanceiroService {
 private final LancamentoFinanceiroRepository repo; private final EmpresaRepository empresaRepo; private final ModuloAcessoService mod; private final ComissaoService comissaoService;
 public FinanceiroService(LancamentoFinanceiroRepository repo,EmpresaRepository empresaRepo,ModuloAcessoService mod,ComissaoService comissaoService){this.repo=repo;this.empresaRepo=empresaRepo;this.mod=mod;this.comissaoService=comissaoService;}
 private Long tenant(){return TenantContext.getRequired();} private void exigir(){mod.exigir(ModuloSistema.FINANCEIRO);}
 @Transactional(readOnly=true) public Page<LancamentoFinanceiro> listar(Pageable p){exigir();return repo.findByEmpresaId(tenant(),p);}
 @Transactional public void criar(FinanceiroRequests.LancamentoForm f){exigir(); if(f.tipo()==TipoLancamentoFinanceiro.RECEITA) throw new RegraNegocioException("Receitas de atendimento são geradas pelo fechamento do atendimento. Cadastre manualmente apenas despesas.");
  if(f.dataVencimento()!=null && f.dataVencimento().isBefore(f.dataMovimento())) throw new RegraNegocioException("O vencimento não pode ser anterior à data do movimento.");
  if(f.tipo()==TipoLancamentoFinanceiro.DESPESA) repo.save(LancamentoFinanceiro.despesa(empresaRepo.findById(tenant()).orElseThrow(()->new ResourceNotFoundException("Empresa não encontrada.")),f.valor(),f.descricao(),f.dataMovimento(),f.dataVencimento(),f.formaPagamento())); }
 @Transactional public void registrarReceitaAtendimento(Atendimento a){if(!mod.possui(ModuloSistema.FINANCEIRO)||a==null||a.getId()==null)return; Long e=tenant(); if(a.getEmpresa()==null||!e.equals(a.getEmpresa().getId())) throw new RegraNegocioException("O atendimento não pertence à empresa atual."); if(repo.existsByAtendimentoIdAndEmpresaId(a.getId(),e))return; if(a.getValorCobrado()==null||a.getValorCobrado().signum()<=0)return; repo.save(new LancamentoFinanceiro(a.getEmpresa(),a,a.getCliente(),a.getValorCobrado(),"Atendimento - "+(a.getServicoNome()==null?a.getTipo():a.getServicoNome()),a.getDataHoraInicio().toLocalDate())); }
 @Transactional public void pagar(Long id,FormaPagamento forma){exigir(); var l=repo.findByIdAndEmpresaId(id,tenant()).orElseThrow(()->new ResourceNotFoundException("Lançamento não encontrado.")); if(forma==null)throw new RegraNegocioException("Informe a forma de pagamento."); l.pagar(forma); comissaoService.gerarParaReceitaPaga(l);}
 @Transactional public void cancelar(Long id){exigir(); var l=repo.findByIdAndEmpresaId(id,tenant()).orElseThrow(()->new ResourceNotFoundException("Lançamento não encontrado.")); l.cancelar();}
 @Transactional(readOnly=true) public BigDecimal total(LocalDate inicio,LocalDate fim,TipoLancamentoFinanceiro tipo){exigir();return repo.total(tenant(),tipo,StatusLancamentoFinanceiro.PAGO,inicio,fim);}
}
